#167730727 Setup Postgres
andela/firestar-backend pull request #1
Opened 2019-08-15 00:10 UTC by dewaleolaoye

#### What does this PR do?
Configure BareFoot Nomad to use PostgreSQL as DB Engine
#### Description of Task to be completed?
Setup Sequelize
#### How should this be manually tested?
After cloning the repo, cd into `src/services` and run `node index.js  
#### What are the relevant pivotal tracker stories?
#167730727

2019-08-15 13:35 UTC, conquext requested changes
This file should go in src/database/config

Also separate configuration concerns from migration services.

2019-08-15 17:06 UTC, marusoft approved these changes
awesome work, work as expected

2019-08-15 20:12 UTC, conquext requested changes
/* Great job centralizing all access to the database to one file
 * You now have to expose the global pool to the app by exporting your setup
 */
module.exports = {
   query: function(text, values, cb) {
      pool.connect(function(err, client, done) {
        client.query(text, values, function(err, result) {
          done();
          cb(err, result);
        })
      });
   }
}

This way you can be able to
1. instantiate the pool in one spot in the app and expose it to all queries.
2. handle 1 query at a time per connection. 
3. control the life-cycle of all connections.
4. open up a 1-off client to kill some hung stuff.
5. share a connection across multiple queries within a request and only have to change things in one place.

You might want to change your call to pool.connect() now to listen for connections instead
i.e. 
pool.on('connect', () => {
  debug('connected to the Database');
});

Also, create a separate database url for test or development environment.

2019-08-15 20:12 UTC, conquext commented on src/database/config.js
> +  .then(() => console.log('connected to db'))
/* Great job centralizing all access to the database to one file
 * You now have to expose the global pool to the app
 */
module.exports = {
   query: function(text, values, cb) {
      pool.connect(function(err, client, done) {
        client.query(text, values, function(err, result) {
          done();
          cb(err, result);
        })
      });
   }
}

This way you can be able to
1. instantiate the pool in one spot in the app and expose it to all queries.
2. handle 1 query at a time per connection. 
3. control the life-cycle of all connections.
4. open up a 1-off client to kill some hung stuff.
5. share a connection across multiple queries within a request and only have to change things in one place.

You might want to change your call to pool.connect() now to listen for connections instead
i.e. 
pool.on('connect', () => {
  debug('connected to the Database');
});

Also, create a separate database url for test or development environment.

2019-08-16 11:03 UTC, dewaleolaoye commented
@conquext Thanks, I will implement it now

2019-08-16 12:22 UTC, conquext commented
@dewaleolaoye This is fine, but what if we need to check out a client from the pool to run several queries in a row in a transaction?

Since node only loads the module once when it's required so only one client object exists and is shared by your entire app. As you're creating the connection manually once at startup then if it ever has an issue (say the server reboots or the socket has a network issue and closes) the app may never recover. 
So I will suggest we tie our connection to the pool to the lifecycle of their use. If it's tied to a request, or the part of the code that's performing an action, then create the client in that function and dispose of it when that piece is done. The psuedocode would be:

module.exports = function query(text, params) {
  return new Promise((resolve, reject) => {
    try {
      const client = pool.connect();
      client.query(text, params)
        .then((res) => {
          resolve(res);
        }).catch((error) => {
          reject(error);
        })
        .finally(() => { client.release() ;});
    } catch (e) {
      reject(e);
    }
  });
};

2019-08-17 02:46 UTC, dewaleolaoye commented on src/database/config.js
> +  .then(() => console.log('connected to db'))
Okay! but in this case, what we need here is to install ***pg*** module and establish a connection with the database. Sequelize handles every other thing needed like query.

2019-08-17 20:52 UTC, conquext approved these changes
I got clarifications that the task requirement was to setup postgres as a db engine for sequelize ORM. So it is clear we won't need to separately configure postgres. This PR is ok to merge.

2019-08-18 21:58 UTC, rovilay commented on src/database/config.js
> +  .then(() => console.log('connected to db'))
@dewaleolaoye Please resolve outdated conversations

2019-08-19 00:15 UTC, dewaleolaoye commented on src/database/config.js
> +  .then(() => console.log('connected to db'))
@rovilay Okay, I will fix it now

2019-08-20 09:11 UTC, merged