#167920214 ES6 Babel Configuration
andela/firestar-backend pull request #12
Opened 2019-08-16 09:45 UTC by wahaaabello

#### What does this PR do?
Set up es6 babel configuration

#### Description of Task to be completed?
- Activate es6 syntax in project using babel
- Add useful plugins for es-next features

#### How should this be manually tested?
- clone the repo
- cd into code base
- use `npm run build` to run babel transpile
- use `npm start` to run the production server using the result of the previous step
- use `npm run start:dev` to run the development server

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#167920214

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-08-16 11:17 UTC, conquext requested changes
ES6: Prefer arrow syntax in function definitions in the following files (not necessarily exhaustive):
* /config/passport.js
* /routes/api/index.js e.g. router.use((err, req, res, next) => {})
* /routes/api/users.js

No (default) export in models, index.js, routes/api

2019-08-16 11:50 UTC, wahaaabello commented
@conquext The changes you requested are not part of the scope of my PR. They are to be implemented using eslint.

2019-08-16 12:16 UTC, marusoft approved these changes
Great job @wahaaabello

2019-08-16 12:29 UTC, conquext commented
> > ES6: Prefer arrow syntax in function definitions in the following files (not necessarily exhaustive):
> > 
> > * /config/passport.js
> > * /routes/api/index.js e.g. router.use((err, req, res, next) => {})
> > * /routes/api/users.js
> > 
> > No (default) export in models, index.js, routes/api
> 
> @conquext The changes you requested are not part of the scope of my PR. They are to be implemented using eslint.

Okay. What about the module exports?

2019-08-16 13:30 UTC, wahaaabello commented
@conquext It is also not part of the scope of my PR.

I am to change from commonjs export to es6 export (which I have done) but I am not to add or remove exports.

2019-08-16 13:42 UTC, conquext commented
> @conquext It is also not part of the scope of my PR.
> 
> I am to change from commonjs export to es6 export (which I have done) but I am not to add or remove exports.
> 
> export style in the `babel.config.js` has to be in commonjs

> *PT Description*: Configure application to use Es6.
@rovilay can you please comment on this?

2019-08-16 14:45 UTC, rovilay commented
> > @conquext It is also not part of the scope of my PR.
> > I am to change from commonjs export to es6 export (which I have done) but I am not to add or remove exports.
> > export style in the `babel.config.js` has to be in commonjs
> 
> > _PT Description_: Configure application to use Es6.
> > @rovilay can you please comment on this?

@wahaaabello the scope of this work includes configuring the app to use es6 and also update all files to es6 syntax.

2019-08-16 14:47 UTC, wahaaabello commented
@rovilay Are you referring to the es5 syntax in the `babel.config.js` file?

2019-08-16 14:59 UTC, wahaaabello commented
@rovilay Are we totally outlawing all use of the `function () {}` function declaration?

2019-08-16 15:03 UTC, wahaaabello commented
I would like to refer all stakeholders to this [article](https://medium.com/@lucasdavidferrero/dont-use-arrow-functions-when-you-use-mongoose-schema-method-190b79f1640c) as to why this may lead to a bug. Which is why I decided not to make the switch to the es6 arrow syntax. I recommend that I should only be use in the right context.

2019-08-16 15:17 UTC, rovilay commented
> I would like to refer all stakeholders to this [article](https://medium.com/@lucasdavidferrero/dont-use-arrow-functions-when-you-use-mongoose-schema-method-190b79f1640c) as to why this may lead to a bug. Basically, arrow functions don’t bind the `this` keyword as the function expression does.
> 
> Which is why I decided not to make the switch to the es6 arrow syntax. I recommend that I should only be use in the right context.
> 
> The `babel.config.js` file on the other hand, is not transpile by babel itself thus it runs in the node context.

@wahaaabello understood, but other files??

2019-08-16 15:18 UTC, wahaaabello commented
@conquext I believe all other file have been accounted for

2019-08-16 16:34 UTC, conquext commented
> > > ES6: Prefer arrow syntax in function definitions in the following files (not necessarily exhaustive):
> > > 
> > > * /config/passport.js
> > > * /routes/api/index.js e.g. router.use((err, req, res, next) => {})
> > > * /routes/api/users.js
> > > 
> > > No (default) export in models, index.js, routes/api
> > 
> > 
> > @conquext The changes you requested are not part of the scope of my PR. They are to be implemented using eslint.
> 
> Okay. What about the module exports?

The exports of index.js, models/ and passport.js are not effected.

2019-08-16 17:50 UTC, wahaaabello commented
@conquext 
The files you mentioned don't have exports, do they?

- src/config/passport.js
`
import passport from 'passport';
import { Strategy as LocalStrategy } from 'passport-local';
import mongoose from 'mongoose';

const User = mongoose.model("User");

passport.use(
    new LocalStrategy(
        {
            usernameField: "user[email]",
            passwordField: "user[password]"
        },
        function(email, password, done) {
            User.findOne({ email: email })
                .then(function(user) {
                    if (!user || !user.validPassword(password)) {
                        return done(null, false, {
                            errors: { "email or password": "is invalid" }
                        });
                    }

                    return done(null, user);
                })
                .catch(done);
        }
    )
);
`

- src/index.js
`
import fs from 'fs';
import http from 'http';
import path from 'path';
import methods from 'methods';
import express from 'express';
import bodyParser from 'body-parser;'
import session from 'express-session';
import cors from 'cors';
import passport from 'passport';
import errorhandler from 'errorhandler';
import mongoose from 'mongoose';
import models from './models/User';
import routes from './routes';
import method_override from 'method-override';
import morgan from 'morgan';

// if (isProduction) {
//     mongoose.connect(process.env.MONGODB_URI);
// } else {
//     mongoose.connect("mongodb://localhost/conduit");
//     mongoose.set("debug", true);
// }

const isProduction = process.env.NODE_ENV === "production";

// Create global app object
const app = express();

app.use(cors());

// swagger config middlewares
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

// Normal express config defaults
app.use(morgan("dev"));
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.use(method_override());
app.use(express.static(__dirname + "/public"));

app.use(
  session({
    secret: 'authorshaven',
    cookie: {maxAge: 60000},
    resave: false,
    saveUninitialized: false,
  })
);

if (!isProduction) {
    app.use(errorhandler());
}

app.use(routes);

/// catch 404 and forward to error handler
app.use(function(req, res, next) {
  const err = new Error('Not Found');
  err.status = 404;
  next(err);
});

/// error handlers

// development error handler
// will print stacktrace
if (!isProduction) {
  app.use(function(err, req, res, next) {
    console.log(err.stack);

    res.status(err.status || 500);

    res.json({
      errors: {
        message: err.message,
        error: err,
      },
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.json({
    errors: {
      message: err.message,
      error: {},
    },
  });
});

// finally, let's start our server...
const server = app.listen(process.env.PORT || 3000, function() {
  console.log('Listening on port ' + server.address().port);
});
`

2019-08-16 18:04 UTC, conquext commented
You have to export app in index.js, passport in passport.js and the mongoose.model("users", UserSchema) in model/User. In a node project, the only way to share javascript files is to export them, with the exception of environment variables that can be accessed via dotenv. So basically, there is no point of any file that is not serving as a module to be imported by other part(s) of the project.

2019-08-16 18:28 UTC, wahaaabello commented
@conquext 
I get the need to export the User model but there is no need to export `app` from `src/index.js` unless maybe we wanted to integrate testing to the project and I don't believe there is any need to export the passport package because I think it is a global field.

But even then, this is not in the scope of my PR. Please understand that I'm trying to change only what is required of me and keep to the scope of my task so I don't break anything.

2019-08-16 18:30 UTC, conquext commented
> @conquext
> I get the need to export the User model but there is no need to export `app` from `src/index.js` unless maybe we wanted to integrate testing to the project and I don't believe there is any need to export the passport package because I think it is a global field.
> 
> But even then, this is not in the scope of my PR. Please understand that I'm trying to change only what is required of me and keep to the scope of my task so I don't break anything.

You are right, the app export is unnecessary, I have withdrawn it. 
Doing the right thing does not break the code, it rather improves it.

2019-08-16 18:58 UTC, wahaaabello commented
@conquext 
I appreciate the feedback but then 
> If It ain't broke, don't fix it.

I assure you the app runs on `npm run start:dev`
Kindly review.

2019-08-16 19:41 UTC, conquext commented
> @conquext
> I appreciate the feedback but then
> 
> > If It ain't broke, don't fix it.
> 
> I assure you the app runs on `npm run start:dev`
> Kindly review.

I believe the code works fine in ES5 as well, the objective of this task is not merely for it to work but for the task to be carried out according to the specifications.

2019-08-17 06:43 UTC, conquext approved these changes

2019-08-18 23:14 UTC, rovilay commented on src/index.js
> +// } else {
Good work. Please remove commented code.

2019-08-19 08:28 UTC, wahaaabello commented on src/index.js
> +// } else {
@rovilay Done!

2019-08-19 08:59 UTC, merged